namespace NeuroVida.Games.Constelacion
{
    /// <summary>
    /// Lista de palabras de Constelación de Palabras, por categoría y por GRUPO (las "constelaciones"). Formato de cada
    /// línea: <c>clave (nombre visible): palabra|variante|variante, palabra, ...</c>. La primera forma es la que se
    /// muestra; las variantes (regionales, femenino, diminutivo que el juego no deduce solo) cuentan como la misma
    /// palabra: decir "chancho" y después "cerdo" es una sola. Una palabra puede estar en varios grupos (el pato es de la
    /// granja, un ave y de río), como en la forma de puntuar de Troyer, Moscovitch y Winocur (1997).
    /// Variantes de Chile y del resto de Latinoamérica y España (palta/aguacate, frutilla/fresa, choclo/maíz/elote...).
    /// Los plurales y diminutivos regulares ("perros", "perrito", "ratoncito") los resuelve <see cref="FluencyContract"/>.
    /// </summary>
    public static class FluencyLexicon
    {
        public const string Animals = @"
casa (de la casa): perro|perra, gato|gata, conejo|coneja, hámster, cobayo|cobaya|cuy|conejillo de indias, hurón, tortuga, loro|lora, canario, periquito, pez dorado|pez de colores, chinchilla, erizo de tierra
granja (de la granja): vaca, toro, cebú, gallina de guinea|gallineta, buey, ternero|ternera, caballo, yegua, potro|potranca, burro|burra|asno, mula, oveja, cordero, carnero, cabra, chivo|chiva, cerdo|chancho|chancha|puerco|cochino|marrano, gallina, gallo, pollo|pollito, pato|pata, ganso|oca, pavo|guajolote, conejo|coneja, llama, alpaca, codorniz
selva (de la selva y la sabana): león|leona, tigre|tigresa, elefante, jirafa, cebra, hipopótamo, rinoceronte, gorila, chimpancé, mono|mona, orangután, leopardo, guepardo|chita, pantera, jaguar, hiena, ñu, antílope, gacela, búfalo, camello, dromedario, avestruz, suricata, jabalí, tucán, guacamayo, perezoso, tapir, oso hormiguero, anaconda, boa, cocodrilo, caimán, lémur, ocelote, panda|oso panda, cobra, pitón, facóquero, okapi, mandril, babuino, murciélago, impala, cerdo hormiguero, boa constrictor|boa constructor
bosque (del bosque y la montaña): oso, lobo|loba, zorro|zorra, ciervo|cierva, venado, alce, ardilla, mapache, castor, puma, lince, búho, lechuza, águila, jabalí, erizo, tejón, zorrillo|mofeta|chingue, marmota, liebre, puercoespín, gato montés, cabra montés, halcón, pájaro carpintero, coyote, bisonte, comadreja, topo, murciélago
sudamerica (de Sudamérica): llama, alpaca, guanaco, vicuña, cóndor, puma, pudú, huemul, chinchilla, vizcacha, ñandú, jaguar, capibara|carpincho, tapir, armadillo|quirquincho, coipo, degú, güiña, colocolo, monito del monte, zorro culpeo, loica, tucán, piraña, anaconda, perezoso, oso hormiguero, ocelote, caimán, flamenco
polar (del frío): oso polar, pingüino, foca, morsa, reno, zorro ártico, lobo ártico, búho nival, narval, beluga, orca, lobo marino|león marino, liebre ártica, buey almizclero, albatros
mar (del mar): tiburón, tiburón blanco, tiburón ballena, tiburón martillo, morena, dugongo, esponja|esponja de mar, anémona|anémona de mar, pez león, fragata, ballena, delfín, orca, pulpo, calamar, medusa|aguaviva, estrella de mar, caballito de mar|caballo de mar|hipocampo, cangrejo, langosta, camarón|gamba, langostino, jaiba, almeja, ostra, mejillón|chorito|choro|cholga, erizo de mar, foca, lobo marino|león marino, morsa, tortuga marina, pez espada, atún, sardina, merluza, salmón, raya|manta raya|manta, anguila, pingüino, gaviota, pelícano, coral, loco, piure, jurel, congrio, corvina, reineta, anchoveta|anchoa, pez payaso, manatí|vaca marina, narval, beluga, cachalote, pejerrey, lenguado, bacalao, caracol de mar, nutria de mar|chungungo, pez globo, barracuda, delfín rosado
rio (de río y lago): pez|pescado|pececito|pescadito, trucha, carpa, bagre, rana, sapo, pato|pata, cisne, garza, flamenco, nutria|huillín, castor, cocodrilo, caimán, hipopótamo, renacuajo, salmón, capibara|carpincho, piraña, ajolote, coipo, martín pescador, pejerrey, anguila, tortuga, cormorán|cuervo de agua, tagua, gavial, cíclido, colimbo
aves (aves): pájaro|ave, águila, halcón, cóndor, búho, lechuza, loro|lora, perico|cotorra, canario, gorrión, paloma, tórtola, golondrina, colibrí|picaflor, pájaro carpintero|carpintero, tucán, pavo real, cuervo, zorzal, chincol, tordo, jilguero, loica, tiuque, queltehue, gaviota, pelícano, flamenco, garza, cigüeña, pingüino, avestruz, ñandú, emú, pato|pata, ganso|oca, cisne, gallina, gallo, pollo|pollito, pavo|guajolote, codorniz, faisán, perdiz, buitre, gavilán, jote|zopilote, petirrojo, ruiseñor, urraca, kiwi, periquito, guacamayo, albatros, cacatúa, martín pescador, cormorán|cuervo de agua, tagua, búho nival, choroy, tenca, chercán, diuca, cernícalo, garza real, grulla, fragata, casuario, avoceta, colimbo, gallina de guinea|gallineta, abubilla, mirlo, estornino, carancho, bandurria
insectos (insectos y bichos): hormiga, abeja, avispa, mosca, mosquito|zancudo, mariposa, polilla, escarabajo, cucaracha, grillo, saltamontes|chapulín, chinita|mariquita|catarina|vaquita de san antonio, libélula|matapiojos|caballito del diablo, pulga, piojo, garrapata, araña, alacrán|escorpión, ciempiés, milpiés, lombriz, gusano, caracol, babosa, luciérnaga, termita, cigarra|chicharra, mantis|mantis religiosa, oruga|cuncuna, tábano, abejorro|moscardón|mangangá, chinche, tijereta, avispón, cochinilla|chanchito de tierra, pololo, madre de la culebra, avispa chaqueta amarilla|chaqueta amarilla, hormiga león, tarántula, viuda negra
reptiles (reptiles y anfibios): serpiente, culebra, víbora, lagarto, lagartija, iguana, camaleón, tortuga, cocodrilo, caimán, anaconda, boa, cobra, pitón, dragón de komodo, rana, sapo, salamandra, ajolote, gecko|geco, tortuga marina, cascabel|serpiente de cascabel, galápago, dinosaurio, renacuajo, gavial, boa constrictor|boa constructor, mamba, serpiente coral
roedores (roedores): ratón|laucha|ratoncito, rata, ardilla, hámster, castor, puercoespín, chinchilla, capibara|carpincho, cobayo|cobaya|cuy|conejillo de indias, degú, marmota, lirón, jerbo, vizcacha, coipo
felinos (felinos): gato|gata, león|leona, tigre|tigresa, leopardo, jaguar, puma, lince, pantera, guepardo|chita, ocelote, gato montés, güiña, colocolo, leopardo de las nieves
caninos (perros y parientes): perro|perra, lobo|loba, zorro|zorra, coyote, chacal, dingo, zorro ártico, lobo ártico, zorro culpeo, fénec
primates (monos): mono|mona, gorila, chimpancé, orangután, babuino, mandril, lémur, tití, macaco, mono araña, mono aullador, bonobo
extintos (de otras épocas): dinosaurio, tiranosaurio, triceratops, velociraptor, pterodáctilo|pteranodon, mamut, mastodonte, tigre dientes de sable|dientes de sable|smilodon, dodo, megaterio, braquiosaurio, estegosaurio
australia (de Australia): canguro, koala|oso koala, ornitorrinco, emú, wombat, dingo, equidna, demonio de tasmania, cacatúa, cocodrilo, casuario, walabí|ualabí
";

        public const string Produce = @"
citricos (cítricos): naranja, limón, mandarina, pomelo|toronja, lima, clementina, kumquat, cidra
tropicales (tropicales): plátano|banana|banano|guineo, piña|ananá|ananás, mango, papaya, mangostán, rambután, tamarindo, noni, açaí|asaí, camu camu, maracuyá|fruta de la pasión, coco, guayaba, kiwi, lúcuma, chirimoya, guanábana, pitahaya|fruta del dragón, carambola, lichi, palta|aguacate, tuna, mamey, pepino dulce, feijoa, caqui|kaki
arbol (de árbol): manzana, pera, durazno|melocotón, damasco|albaricoque|chabacano, ciruela, cereza, guinda, nectarín, membrillo, níspero, higo|breva, granada, caqui|kaki, aceituna|oliva, castaña, nuez, almendra, avellana, pistacho, piñón, dátil, coco, limón, naranja, mandarina, palta|aguacate, mango
berries (frutos del bosque): frutilla|fresa, frambuesa, mora|zarzamora, arándano, grosella, grosella negra|casis, murta|murtilla, mora blanca, maqui, calafate, uva, cranberry|arándano rojo, zarzaparrilla, mora de árbol
verano (de verano): sandía|patilla, melón, melón tuna, pepino dulce, durazno|melocotón, frutilla|fresa, cereza, damasco|albaricoque|chabacano, ciruela, uva, nectarín, frambuesa, arándano, mora|zarzamora, tuna, higo|breva
secos (frutos secos): nuez, almendra, avellana, maní|cacahuate|cacahuete, castaña, pistacho, piñón, anacardo|castaña de cajú, pasa|pasas|uva pasa, ciruela seca, dátil, higo seco, nuez de brasil, macadamia
hojas (de hoja): lechuga, espinaca, acelga, repollo|col, kale|col rizada, rúcula|rúgula, berro, apio, endivia, achicoria, escarola, repollo morado, hinojo
hierbas (hierbas y aliños): cilantro|culantro, perejil, albahaca, orégano, menta, hierbabuena|yerbabuena, romero, tomillo, ciboulette|cebollín|cebolleta, laurel, eneldo, estragón, salvia, jengibre, ajo, comino, merkén, ají
raices (raíces y bulbos): papa|patata, camote|batata|boniato, zanahoria, betarraga|remolacha|betabel, rábano, nabo, yuca|mandioca, jengibre, cebolla, ajo, puerro|porro, chalota, jícama, cebolla morada, rabanito, apionabo, topinambur, olluco, oca
fruto (verduras de fruto): tomate|jitomate, pimiento|pimentón|morrón|chile morrón, ají|chile, berenjena, zapallo|calabaza|auyama, zapallito italiano|zucchini|calabacín|zapallito, pepino, choclo|maíz|elote, aceituna|oliva, zapallo camote, tomate cherry, ají verde, chile verde
flores (flores, brotes y hongos): champiñón|hongo|callampa|seta, brócoli|brécol, coliflor, alcachofa|alcaucil, espárrago, repollito de bruselas|col de bruselas|coles de bruselas, brote de soya|brotes de soya, alfalfa, flor de calabaza, romanesco
legumbres (legumbres y porotos): poroto|frijol|judía|fréjol|caraota, lenteja, garbanzo, arveja|guisante|chícharo, haba, soya|soja, poroto verde|chaucha|habichuela|vainita|judía verde|ejote, poroto granado, lupino|chocho|altramuz, porotos negros|frijoles negros
";

        public const string House = @"
cocina (de la cocina): cocina|estufa de cocina, horno, microondas, refrigerador|refri|nevera|heladera|frigorífico|refrigeradora, lavaplatos|fregadero, lavavajillas, olla, sartén, tetera, hervidor, cuchara, cuchillo, tenedor, plato, vaso, taza|tazón, jarro, jarra, tabla de picar, colador, batidora, licuadora, tostadora|tostador, cafetera, rallador, cucharón, espátula, bandeja, fuente, mantel, servilleta, delantal|pechera, alacena, despensa, paño de cocina|repasador, abrelatas, sacacorchos, frasco, salero, azucarero, panera, olla a presión, uslero|rodillo, cubiertos, copa, termo, individual, basurero|tacho de basura|cubo de basura, mesón|encimera, campana, congelador|freezer, hielera, ensaladera
bano (del baño): inodoro|excusado|wáter|váter|taza del baño, lavamanos|lavabo, ducha, tina|bañera|bañadera, espejo, toalla, jabón, champú|shampoo, acondicionador, cepillo de dientes, pasta de dientes|pasta dental|dentífrico, papel higiénico|papel confort, peineta|peine, secador de pelo|secador, pesa|balanza, cortina de baño, esponja, alfombra de baño|piso de baño, botiquín, hilo dental, crema, desodorante, perfume, afeitadora|máquina de afeitar|rasuradora, algodón, cotonito|cotonete|hisopo, bidé, toallero
dormitorio (del dormitorio): cama, almohada, sábana, frazada|manta|cobija|cobertor, colcha, plumón|edredón|acolchado, velador|mesita de noche|mesa de noche, lámpara, ropero|clóset|armario|placard, cómoda, despertador, colchón, cortina, percha|gancho|colgador, pijama, cuna, camarote|litera, tocador, alfombra, espejo, baúl, zapatero, cubrecama, funda, cojín|almohadón
living (del living y el comedor): sofá|diván, sillón, silla, mesa, televisor|tele|televisión|tv, alfombra, cuadro, estante|repisa, librero|biblioteca, lámpara, cojín|almohadón, cortina, chimenea, estufa, radio, parlante|altavoz|bocina, control remoto|control, florero, reloj, piano, mesa de centro, aparador|bufé, comedor, sitial, puf, persiana, calefactor, ventilador, planta, adorno, marco de fotos|portarretrato, mecedora
lavadero (de limpieza y lavado): escoba, pala, trapero|mopa|fregona|lampazo, balde|cubeta|cubo, aspiradora, plancha, tabla de planchar, lavadora, secadora, tendedero|cordel|colgador de ropa, perro de ropa|pinza de ropa|broche, detergente, cloro|lejía|lavandina, esponja, paño, virutilla, plumero, recogedor, canasto de ropa|cesto, guantes, jabón
herramientas (herramientas): martillo, destornillador|desatornillador, alicate|pinza, taladro, serrucho|sierra, clavo, tornillo, llave inglesa, escalera, huincha|cinta métrica|metro, linterna, nivel, lija, cinta aislante, alargador|extensión, pegamento, tijeras, cuchillo cartonero|cúter, caja de herramientas, destornillador eléctrico, tuerca, taladro eléctrico
jardin (del jardín y el patio): manguera, regadera, rastrillo, macetero|maceta, cortacésped|cortapasto, parrilla|asador, reja, piscina, columpio, hamaca, bicicleta, tijera de podar, carretilla, banca|banco, quitasol|sombrilla, tendedero, pala, reposera|silla de playa, casa del perro, buzón, farol, fuente de agua
entrada (puertas y ventanas): puerta, ventana, timbre, llave, cerradura|chapa, felpudo|limpiapiés, mampara, portón, escalera, pasillo, techo, piso|suelo, pared|muralla, balcón, terraza, garaje|garage|cochera, ascensor, citófono|portero eléctrico|intercomunicador
estudio (del escritorio): computador|computadora|ordenador|pc, notebook|laptop|portátil, escritorio, silla, lápiz|lapicero|bolígrafo|birome|lápiz pasta, cuaderno, libro, impresora, teléfono, celular|móvil|smartphone, cargador, calculadora, tijeras, pegamento, calendario, agenda, goma|borrador, sacapuntas|tajador, regla, mochila, estuche, tablet|tableta, audífonos|auriculares, mouse|ratón, teclado, pantalla|monitor, enchufe, carpeta, archivador, corchetera|engrapadora, clip
";
    }
}
